// Static, hand-curated index of everything searchable across the member site.
// There's no CMS/database backing Resources/Templates/Webinars — content lives in
// per-page arrays and hand-written JSX — so this index is maintained by hand
// alongside those pages rather than generated.

export type SearchEntry = {
  title: string;
  description: string;
  category: string;
  type: string;
  href: string;
  external?: boolean; // opens in a new tab (static /tools/*.html pages)
};

export const searchIndex: SearchEntry[] = [
  // ── Home ──────────────────────────────────────────────────────────────────
  { title: "Dashboard", description: "Your member home base — quick links to Templates, Webinars, and Resources plus recent activity.", category: "Home", type: "Page", href: "/members/dashboard" },
  { title: "All Resources", description: "Browse every resource category — Marketing, Operations, Finance, and Staff.", category: "Home", type: "Page", href: "/members/resources" },

  // ── Operations ────────────────────────────────────────────────────────────
  { title: "Consultation Conversion Tracker", description: "Log consultations by provider and service type, then run reports by date range to see conversion rates and track notes on what drove the numbers.", category: "Operations", type: "Tool", href: "/members/resources/operations/consultation-conversion-tracker" },
  { title: "Goal Tracker", description: "Set a target for the period, log progress and business days remaining, and see exactly what you need per business day to hit it. Printable worksheet, saved by name and date range.", category: "Operations", type: "Tool", href: "/members/resources/operations/goal-tracker" },
  { title: "Goal Setting Guide", description: "Suggested goals across revenue, acquisition, retention, and provider productivity, plus why breaking big goals into weekly and daily pace keeps a team on track.", category: "Operations", type: "Guide", href: "/members/resources/operations/goal-setting-guide" },
  { title: "Cross-Selling Tool", description: "Brainstorm cross-sell combos, audit performance, map the patient journey, and build a training and tracking plan, pre-loaded with example journey stages and metrics.", category: "Operations", type: "Tool", href: "/members/resources/operations/cross-selling-tool" },
  { title: "Maximizing Cross-Selling Guide", description: "The 7-step process for defining cross-sells, mapping the patient journey, building tools, and training your team to sell with confidence.", category: "Operations", type: "Guide", href: "/members/resources/operations/cross-selling-guide" },
  { title: "Inventory Management System", description: "Track products by category, vendor, unit, and cost. Log physical counts and incoming stock, see live on-site dollar value, and get red/yellow par-level alerts.", category: "Operations", type: "Tool", href: "/members/resources/operations/inventory-management" },
  { title: "Opening & Closing Checklist Builder", description: "Pre-loaded MedSpa opening and closing duties — toggle, edit, add your own, set frequency, and print a branded checklist with checkbox, initials, and date lines.", category: "Operations", type: "Tool", href: "/members/resources/operations/opening-closing-checklist" },
  { title: "Patient Intake Form Builder", description: "Build a branded patient intake form — toggle or edit 34 pre-loaded concern questions across 4 sections, add your own, and print or save as PDF.", category: "Operations", type: "Tool", href: "/members/resources/operations/intake-form-builder" },
  { title: "Treatment Plan Builder", description: "Build a branded, print-ready treatment plan with up to 6 treatment blocks, pricing, a home care product table, and notes.", category: "Operations", type: "Tool", href: "/members/resources/operations/treatment-plan-builder" },
  { title: "Secret Shopper Log", description: "Log every secret shop — own practice or competitor — across all 9 questionnaire sections with photo uploads and scoring.", category: "Operations", type: "Tool", href: "/tools/secret-shopper-log.html", external: true },
  { title: "Why Secret Shop?", description: "The strategy behind secret shopping — why to shop yourself and competitors, cadence, debriefing, and what to do with results.", category: "Operations", type: "Guide", href: "/members/resources/operations/secret-shopping" },
  { title: "Printable Secret Shopper Questionnaire", description: "All 9 sections with write-in lines and scoring boxes, formatted for print.", category: "Operations", type: "Print / PDF", href: "/tools/secret-shopper-questionnaire.html", external: true },

  // ── Marketing ─────────────────────────────────────────────────────────────
  { title: "Treatment Landing Pages", description: "SEO + conversion playbook for building treatment pages that rank in Google and turn visits into booked consultations.", category: "Marketing", type: "Guide", href: "/members/resources/marketing/landing-pages" },
  { title: "SEO & Online Visibility Guide", description: "How Google ranks your practice, the 10 factors that determine visibility, and quick wins.", category: "Marketing", type: "Guide", href: "/members/resources/marketing/seo-guide" },
  { title: "AI SEO Analyzer", description: "Enter your website URL and get an AI-powered scan of all 10 SEO ranking factors with what to fix.", category: "Marketing", type: "Tool", href: "/tools/seo-analyzer.html", external: true },
  { title: "Google Business Profile", description: "Complete SOP for ranking in Google's Local Map Pack — setup, services, photos, posts, and a monthly checklist.", category: "Marketing", type: "Guide", href: "/members/resources/marketing/google-business-profile" },
  { title: "Google Reviews", description: "A practical system for collecting reviews consistently — the ask script, automation flow, and team culture.", category: "Marketing", type: "Guide", href: "/members/resources/marketing/google-reviews" },
  { title: "Monthly Features", description: "How to plan monthly features that grow revenue without discounting, plus an interactive marketing calendar.", category: "Marketing", type: "Guide", href: "/members/resources/marketing/monthly-features" },
  { title: "Promo Calendar Tool", description: "Plan and track features, campaigns, and events across the year with notes and performance metrics per entry.", category: "Marketing", type: "Tool", href: "/tools/promo-calendar.html", external: true },
  { title: "Blog Strategy", description: "How to turn your website into a patient-generating machine with consistent blog content — topics, structure, and repurposing.", category: "Marketing", type: "Guide", href: "/members/resources/marketing/blog-strategy" },
  { title: "Email & Text Marketing", description: "How to use email and text to increase retention, reactivate lapsed patients, and fill your schedule.", category: "Marketing", type: "Guide", href: "/members/resources/marketing/email-text-marketing" },
  { title: "Automated Campaigns", description: "15 automated campaigns your practice should have running — acquisition, retention, reactivation, and revenue.", category: "Marketing", type: "Guide", href: "/members/resources/marketing/automated-campaigns" },
  { title: "Meta Ads", description: "A practical guide to profitable Facebook and Instagram advertising for aesthetic practices.", category: "Marketing", type: "Guide", href: "/members/resources/marketing/meta-ads" },
  { title: "Google Ads", description: "How to build profitable Google Search campaigns — keyword tiers, negative keywords, and Quality Score.", category: "Marketing", type: "Guide", href: "/members/resources/marketing/google-ads" },
  { title: "Before & After Photography", description: "A complete protocol for lighting, angles, patient prep, and HIPAA-compliant consent for before/after photos.", category: "Marketing", type: "Guide", href: "/members/resources/marketing/before-after-photos" },
  { title: "Event Planning", description: "123-item interactive checklist covering pre-event planning, day-of execution, and post-event follow-up.", category: "Marketing", type: "Guide", href: "/members/resources/marketing/event-planning" },
  { title: "Event Planner Tool", description: "Create events, mark items done/pending/N-A, add notes, and watch a color-coded progress bar update live.", category: "Marketing", type: "Tool", href: "/tools/event-planner.html", external: true },
  { title: "Social Media Best Practices", description: "The 5 P's, push vs. pull marketing, content categories, post anatomy, and a pre-post checklist.", category: "Marketing", type: "Guide", href: "/members/resources/marketing/social-media" },
  { title: "Patient Referral Program", description: "A 12-step system for building a patient referral program that generates consistent new patient growth.", category: "Marketing", type: "Guide", href: "/members/resources/marketing/patient-referral" },
  { title: "Referral Partner Program", description: "Build a structured 'Give $50, Get $50' referral program with hairstylists, lash artists, and other providers.", category: "Marketing", type: "Guide", href: "/members/resources/marketing/referral-partners" },
  { title: "Strategic Community Partnerships", description: "Build cross-promotional relationships with gyms, yoga studios, boutiques, and wellness centers.", category: "Marketing", type: "Guide", href: "/members/resources/marketing/community-partnerships" },
  { title: "Brand Kit Builder", description: "Document your brand's mission, values, color palette, typography, voice, and target client — export a formatted brand kit.", category: "Marketing", type: "Tool", href: "/tools/brand-kit-builder.html", external: true },
  { title: "Why Your Brand Kit Matters", description: "Why an intentional brand matters and what goes into a complete brand kit before you start building yours.", category: "Marketing", type: "Guide", href: "/members/resources/marketing/brand-kit" },
  { title: "Ideal Client Builder", description: "Build three detailed ideal client personas plus your brand personality, voice, and promise — export for agencies.", category: "Marketing", type: "Tool", href: "/tools/ideal-client-builder.html", external: true },
  { title: "Lead Conversion Playbook", description: "A step-by-step system for responding to, nurturing, and converting new patient inquiries into treatments.", category: "Marketing", type: "Guide", href: "/members/resources/marketing/lead-conversion" },
  { title: "Membership + Rewards Audit Tool", description: "Audit your in-house membership and Allē, Aspire, Evolus & Reva rewards enrollment, assess promotion, and build an action and tracking plan.", category: "Marketing", type: "Tool", href: "/members/resources/marketing/membership-rewards-audit" },
  { title: "Maximizing In-House Memberships + Rewards Programs Guide", description: "The 8-step process for auditing, promoting, and tracking your in-house membership and manufacturer rewards programs.", category: "Marketing", type: "Guide", href: "/members/resources/marketing/membership-rewards-guide" },

  // ── Finance & Business Performance ───────────────────────────────────────
  { title: "Treatment Profitability Analyzer", description: "Enter price and direct costs per treatment to see net profit and margin, with 15 pre-loaded services.", category: "Finance", type: "Tool", href: "/members/resources/finance/treatment-profitability" },
  { title: "Budget & Financial Dashboard", description: "Four-tab interactive dashboard — annual budget, monthly expense tracking, quarterly rollups, and KPI benchmarking.", category: "Finance", type: "Tool", href: "/members/resources/finance/budget-tracker" },
  { title: "Budget Tracker Tool", description: "Open the interactive budget tracker directly — revenue entry, CSV expense import, and variance tracking.", category: "Finance", type: "Tool", href: "/tools/budget-tracker.html", external: true },
  { title: "KPI Tracker", description: "Track all 16 key performance indicators month over month, tagged by team member, with benchmarks and trends.", category: "Finance", type: "Tool", href: "/members/resources/finance/kpi-tracker" },
  { title: "Med Spa P&L Guide", description: "What to track, how to categorize every dollar, and how to interpret the numbers for your practice.", category: "Finance", type: "Guide", href: "/members/resources/finance/pl-guide" },
  { title: "SWOT Analysis Tool", description: "Work through Strengths, Weaknesses, Opportunities, and Threats with guided prompts, star your priorities, and build a 30-day action plan. Save each quarter by name.", category: "Finance", type: "Tool", href: "/members/resources/finance/swot-analysis" },
  { title: "SWOT Analysis Guide", description: "What a SWOT analysis is, why to run one every quarter, and how to turn it into a real 30-day action plan.", category: "Finance", type: "Guide", href: "/members/resources/finance/swot-analysis-guide" },
  { title: "Monthly & Annual P&L Template", description: "Four-tab Excel workbook with pre-built formulas for gross margin, payroll %, net profit, and 9 KPI metrics.", category: "Finance", type: "Template", href: "/downloads/ae-pl-template.xlsx" },
  { title: "Business Plan Tool", description: "Build your vision, revenue and profit milestones, goals, staffing forecast, and market-risk plan across 1, 5, and 10-year horizons.", category: "Finance", type: "Tool", href: "/members/resources/finance/business-plan" },
  { title: "1, 5, and 10-Year Business Plan Guide", description: "How to build a long-term business plan — vision, milestones, goals, staffing, market shifts, and a review cadence for each horizon.", category: "Finance", type: "Guide", href: "/members/resources/finance/business-plan-guide" },

  // ── Staff ─────────────────────────────────────────────────────────────────
  { title: "Onboarding Checklist Builder", description: "Start from a Provider or Support Staff template, add or remove criteria, and save as many named onboarding checklists as you need — each prints as a clean sign-off document.", category: "Staff", type: "Tool", href: "/members/resources/staff/onboarding-checklist" },
  { title: "Onboarding Guide", description: "Why a signed-off onboarding checklist matters, the three parts every onboarding covers, and how to run it well with a new hire.", category: "Staff", type: "Guide", href: "/members/resources/staff/onboarding-guide" },
  { title: "Meeting Notes", description: "Pre-loaded with the recommended staff meeting agenda — add, remove, or reorder sections, then log notes for every meeting under a name and date.", category: "Staff", type: "Tool", href: "/members/resources/staff/meeting-notes" },
  { title: "Staff Meeting Agenda", description: "A six-part recurring team meeting structure — what to cover, why each part matters, and tips for running it well.", category: "Staff", type: "Guide", href: "/members/resources/staff/staff-meeting-agenda" },
  { title: "Job Post Generator", description: "Answer a few questions and get a complete, polished job post in seconds — covers 7 roles.", category: "Staff", type: "Tool", href: "/tools/job-post-generator.html", external: true },
  { title: "Interview Guide Generator", description: "Generate a three-stage interview guide built on the MBI framework — skill, attitude, and passion.", category: "Staff", type: "Tool", href: "/tools/interview-guide-generator.html", external: true },
  { title: "Offer Letter Builder", description: "A complete employment offer letter with every standard section already written — fill in candidate details, edit the final copy, then save as a PDF or copy it for email.", category: "Staff", type: "Tool", href: "/members/resources/staff/offer-letter" },
  { title: "Core Values Generator", description: "AI distills your authentic core values from reflective questions about your team's best moments.", category: "Staff", type: "Tool", href: "/tools/core-values-generator.html", external: true },
  { title: "Living Your Values", description: "7 activation areas — hiring, daily ops, recognition, meetings, and performance reviews — for embedding culture.", category: "Staff", type: "Guide", href: "/members/resources/staff/embed-values" },
  { title: "Mission Statement Generator", description: "Answer reflective questions about your purpose and patients — AI drafts three mission statement options.", category: "Staff", type: "Tool", href: "/tools/mission-statement-generator.html", external: true },
  { title: "Team Health Assessment", description: "Rate your team across 8 key areas — trust, communication, recognition — with a strategy builder and history tracking.", category: "Staff", type: "Tool", href: "/tools/team-satisfaction.html", external: true },
  { title: "Management Structure Builder", description: "Build a responsibility library and drag-and-drop every responsibility onto a full monthly calendar.", category: "Staff", type: "Tool", href: "/tools/management-structure.html", external: true },
  { title: "Handling Escalated Clients", description: "How to de-escalate difficult clients and resolve concerns using the 7-step LEAP FWD framework.", category: "Staff", type: "Training", href: "/members/resources/staff/escalated-customer-service" },
  { title: "Presenting Patient Financing", description: "How to introduce financing options confidently — a 6-step talk track with word-for-word scripts.", category: "Staff", type: "Training", href: "/members/resources/staff/patient-financing" },
  { title: "The Art of the Consult", description: "Complete conversion playbook from first inquiry to closed treatment plan, with objection handling.", category: "Staff", type: "Training", href: "/members/resources/staff/sales-process" },
  { title: "Phone Call Mastery", description: "A 10-step framework for turning every inbound call into a booked, confident patient.", category: "Staff", type: "Training", href: "/members/resources/staff/phone-call-mastery" },
  { title: "In-Office Sales Mastery", description: "Cross-selling framework and scripts for in-person device treatments, plus the arrival experience.", category: "Staff", type: "Training", href: "/members/resources/staff/front-desk-sales" },
  { title: "Employee File Guide", description: "The 6 required file categories, retention schedules, compliance traps, and a maintenance plan.", category: "Staff", type: "Guide", href: "/members/resources/staff/employee-files" },
  { title: "12-Week Leadership Development", description: "A self-paced curriculum built around 8 leadership books, TED talks, and podcasts with weekly reflections.", category: "Staff", type: "Course", href: "/members/resources/staff/leadership-course" },
  { title: "Employee Evaluation Forms", description: "Role-specific evaluation forms for Patient Care Coordinator, Med Spa Manager, and Provider/Injector, plus the review process.", category: "Staff", type: "Template", href: "/members/resources/staff" },
  { title: "Employee Write-Up Form", description: "A structured write-up template with editable warning levels, violation categories, and disciplinary actions — save named records and print for sign-off.", category: "Staff", type: "Tool", href: "/members/resources/staff/employee-write-up-form" },
  { title: "Documentation & Write-Up Guide", description: "Why documenting out-of-the-ordinary employee behavior matters, what's worth writing down, and how to do it well.", category: "Staff", type: "Guide", href: "/members/resources/staff/employee-write-up-guide" },

  // ── Templates ─────────────────────────────────────────────────────────────
  { title: "Event RSVP Tracking Sheet", description: "Track attendee RSVPs, contact information, and attendance for practice events and treatment nights.", category: "Templates", type: "Template", href: "/templates/event-rsvp-sheet.xlsx" },
  { title: "Employee Social Media Policy", description: "Customizable social media policy covering professional representation, HIPAA, and brand standards.", category: "Templates", type: "Template", href: "/templates/employee-social-media-policy.docx" },
  { title: "Treatment Profitability Template", description: "Three-tab Excel workbook pre-loaded with 15 common treatments — auto-calculating profit and margin with conditional color coding.", category: "Templates", type: "Template", href: "/downloads/ae-treatment-profitability.xlsx" },
  { title: "Patient Care Coordinator Evaluation Form", description: "Role-specific performance evaluation covering service quality, communication, scheduling, and patient experience.", category: "Templates", type: "Template", href: "/downloads/Patient-Care-Coordinator-Evaluation.docx" },
  { title: "Med Spa Manager Evaluation Form", description: "Role-specific performance evaluation covering leadership, operations, revenue management, and team development.", category: "Templates", type: "Template", href: "/downloads/Med-Spa-Manager-Evaluation.docx" },
  { title: "Provider / Injector Evaluation Form", description: "Role-specific performance evaluation covering clinical skill, patient consultation, safety protocol, and treatment outcomes.", category: "Templates", type: "Template", href: "/downloads/Provider-Injector-Evaluation.docx" },
  { title: "Strategic Community Partnerships Guide", description: "The full Community Partnerships playbook as a shareable Word doc.", category: "Templates", type: "Template", href: "/templates/community-partnerships.docx" },
  { title: "Patient Referral Program Guide", description: "The full 12-step patient referral program playbook as a shareable Word doc.", category: "Templates", type: "Template", href: "/templates/patient-referral-program.docx" },
  { title: "Referral Partner Program Guide", description: "The full Referral Partner Program playbook as a shareable Word doc.", category: "Templates", type: "Template", href: "/templates/referral-partner-program.docx" },
];
